# ---------------------------------------------------------------------------
#!/usr/bin/env bash
#
# Description: 
# 	system_info.sh
# 	Collects detailed system information for RHEL 8 (Dell or other hardware).
# 	Output is saved as system_info_<hostname>_<timestamp>.log in the current dir.
#   Generates both text and HTML reports.
# Author:      peddycoartte
# Created:     2025-11-10 13:00:40
# Usage:       
# ---------------------------------------------------------------------------
#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# system_info.sh
# Collects detailed system information for RHEL 8 (Dell or other hardware).
# Generates both text and HTML reports.
# ---------------------------------------------------------------------------

set -euo pipefail
export LC_ALL=C

# --- Setup ---
HOSTNAME="$(hostname)"
TIMESTAMP="$(date '+%Y-%m-%d_%H-%M-%S')"
OUT_TXT="system_info_${HOSTNAME}_${TIMESTAMP}.log"
OUT_HTML="system_info_${HOSTNAME}_${TIMESTAMP}.html"

echo "📘 Collecting system information for ${HOSTNAME} ..."
echo "📁 Output: $OUT_TXT and $OUT_HTML"

# --- Helper Functions ---
divider() { echo "--------------------------------------------------------------------------"; }
section()  { echo -e "\n$(divider)\n🧩 $1\n$(divider)\n"; }

# HTML helpers
html_escape() { sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'; }
html_header() {
cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>System Info - ${HOSTNAME}</title>
<style>
body { font-family: monospace; background: #f9f9f9; color: #222; margin: 20px; }
h2 { background: #005fa3; color: white; padding: 6px 10px; border-radius: 5px; cursor: pointer; }
pre { background: #fff; border: 1px solid #ccc; padding: 10px; border-radius: 6px; overflow-x: auto; }
details { margin-bottom: 12px; }
summary { font-weight: bold; }
footer { font-size: 0.9em; color: #555; margin-top: 20px; }
</style>
</head>
<body>
<h1>System Information Report</h1>
<p><b>Host:</b> ${HOSTNAME}<br>
<b>Date:</b> $(date)<br>
<b>Generated by:</b> $(whoami)</p>
EOF
}

html_footer() {
cat <<EOF
<footer>Generated by system_info.sh on $(date)</footer>
</body></html>
EOF
}

add_html_section() {
  local title="$1"
  local cmd="$2"
  echo "<details open><summary>${title}</summary><pre>" >> "$OUT_HTML"
  eval "$cmd" 2>&1 | html_escape >> "$OUT_HTML" || true
  echo "</pre></details>" >> "$OUT_HTML"
}

# --- Initialize files ---
echo "System Information Report for ${HOSTNAME}" > "$OUT_TXT"
divider >> "$OUT_TXT"
html_header > "$OUT_HTML"

# --- 1. System Model ---
section "1. System Model and Manufacturer" | tee -a "$OUT_TXT"
sudo dmidecode -t system | grep -E "Manufacturer|Product|Version|Serial" | tee -a "$OUT_TXT" || true
add_html_section "1. System Model and Manufacturer" \
  "sudo dmidecode -t system | grep -E 'Manufacturer|Product|Version|Serial'"

# --- 2. BIOS Info ---
section "2. BIOS Information" | tee -a "$OUT_TXT"
sudo dmidecode -t bios | grep -E "Vendor|Version|Release" | tee -a "$OUT_TXT" || true
add_html_section "2. BIOS Information" "sudo dmidecode -t bios | grep -E 'Vendor|Version|Release'"

# --- 3. CPU Info ---
section "3. CPU Information" | tee -a "$OUT_TXT"
lscpu | tee -a "$OUT_TXT"
add_html_section "3. CPU Information" "lscpu"

# --- 4. Memory Info ---
section "4. Memory Information" | tee -a "$OUT_TXT"
lsmem | tee -a "$OUT_TXT"
sudo dmidecode -t memory | grep -E "Size:|Locator:" | tee -a "$OUT_TXT" || true
add_html_section "4. Memory Information" "lsmem; sudo dmidecode -t memory | grep -E 'Size:|Locator:'"

# --- 5. Storage ---
section "5. Storage Devices" | tee -a "$OUT_TXT"
lsblk -o NAME,SIZE,MODEL,TYPE,MOUNTPOINT | tee -a "$OUT_TXT"
sudo lshw -class storage -class disk 2>/dev/null | tee -a "$OUT_TXT" || true
add_html_section "5. Storage Devices" "lsblk -o NAME,SIZE,MODEL,TYPE,MOUNTPOINT; sudo lshw -class storage -class disk 2>/dev/null"

# --- 6. GPU ---
section "6. GPU / Display Controllers" | tee -a "$OUT_TXT"
lspci | grep -E "VGA|3D" | tee -a "$OUT_TXT"
for gpu in $(lspci | awk '/VGA/{print $1}'); do
  echo "Details for GPU $gpu:" | tee -a "$OUT_TXT"
  sudo lspci -v -s "$gpu" | tee -a "$OUT_TXT"
done
add_html_section "6. GPU / Display Controllers" "lspci | grep -E 'VGA|3D'; for g in \$(lspci | awk '/VGA/{print \$1}'); do echo 'Details for GPU '\$g; sudo lspci -v -s \$g; done"

# --- 7. Network ---
section "7. Network Interfaces" | tee -a "$OUT_TXT"
nmcli device status | tee -a "$OUT_TXT"
lspci | grep -i ethernet | tee -a "$OUT_TXT"
add_html_section "7. Network Interfaces" "nmcli device status; lspci | grep -i ethernet"

# --- 8. Hardware Summary ---
section "8. Hardware Summary" | tee -a "$OUT_TXT"
sudo lshw -short 2>/dev/null | tee -a "$OUT_TXT" || true
add_html_section "8. Hardware Summary" "sudo lshw -short 2>/dev/null"

# --- 9. DMI / Baseboard ---
section "9. DMI / Baseboard / Chassis" | tee -a "$OUT_TXT"
sudo dmidecode -t chassis -t baseboard | grep -E "Manufacturer|Product|Version|Serial" | tee -a "$OUT_TXT" || true
add_html_section "9. DMI / Baseboard / Chassis" "sudo dmidecode -t chassis -t baseboard | grep -E 'Manufacturer|Product|Version|Serial'"

# --- 10. OS / Kernel / Uptime ---
section "10. OS / Kernel / Uptime" | tee -a "$OUT_TXT"
uname -a | tee -a "$OUT_TXT"
cat /etc/redhat-release | tee -a "$OUT_TXT"
uptime -p | tee -a "$OUT_TXT"
add_html_section "10. OS / Kernel / Uptime" "uname -a; cat /etc/redhat-release; uptime -p"

# --- 11. Disk Usage ---
section "11. Disk Usage" | tee -a "$OUT_TXT"
df -hT | tee -a "$OUT_TXT"
add_html_section "11. Disk Usage" "df -hT"

# --- 12. Dell SMBIOS (optional) ---
if command -v smbios-token-ctl &>/dev/null; then
  section "12. Dell SMBIOS Tokens" | tee -a "$OUT_TXT"
  sudo smbios-token-ctl --list | tee -a "$OUT_TXT" || true
  add_html_section "12. Dell SMBIOS Tokens" "sudo smbios-token-ctl --list"
fi

# --- Footer ---
section "✅ Completed at $(date)" | tee -a "$OUT_TXT"
html_footer >> "$OUT_HTML"

echo
echo "✅ Reports generated:"
echo "   • $OUT_TXT"
echo "   • $OUT_HTML"
echo "Open the HTML report in your browser for a colorized summary."
echo
