#!/usr/bin/env bash
# compare_repo_variants_V5.6.sh — Forensic Edition (modular)
# Generated by ChatGPT for jsigconversiontools multi-backup analysis.
# Features:
#   - Forensic mode: find where you last worked across multiple backup copies
#   - Standard mode: simple table of repos (branch, dirty, last commit)
#   - ASCII timeline of repo activity
#   - HTML forensic report (for browser inspection)
#
# Usage example:
#   ./compare_repo_variants_V5.6.sh \
#       --root-folder /run/media/peddycoartte/MasterBackup/Nightly \
#       --repo-name jsigconversiontools \
#       --mode forensic
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load modules
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/repo_scan.sh"
source "$SCRIPT_DIR/lib/mode_standard.sh"
source "$SCRIPT_DIR/lib/mode_forensic.sh"

MODE="standard"
ROOT_FOLDER=""
REPO_NAME=""

print_main_help() {
    cat <<EOF
compare_repo_variants_V5.6.sh — Forensic Edition

Usage:
  $0 --root-folder <path> --repo-name <name> [--mode standard|forensic]

Required:
  --root-folder <path>    Root directory containing dated backup folders
  --repo-name <name>      Repo folder prefix (e.g. jsigconversiontools)

Modes:
  --mode standard         Show simple table of repos (branch, dirty, last commit)
  --mode forensic         Reconstruct "where you last worked" using:
                            - last commit timestamps
                            - latest file modification timestamps
                            - dirty/staged/untracked counts
                            - ASCII activity timeline
                            - HTML forensic report

Examples:
  $0 --root-folder /run/media/peddycoartte/MasterBackup/Nightly \
     --repo-name jsigconversiontools --mode forensic

  $0 --root-folder /backups --repo-name myproject --mode standard
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --root-folder)
            ROOT_FOLDER="$2"; shift 2;;
        --repo-name)
            REPO_NAME="$2"; shift 2;;
        --mode)
            MODE="$2"; shift 2;;
        --help|-h)
            print_main_help; exit 0;;
        *)
            echo "Unknown option: $1" >&2
            print_main_help
            exit 1;;
    esac
done

if [[ -z "$ROOT_FOLDER" || -z "$REPO_NAME" ]]; then
    echo "ERROR: --root-folder and --repo-name are required." >&2
    print_main_help
    exit 1
fi

if [[ ! -d "$ROOT_FOLDER" ]]; then
    echo "ERROR: root folder does not exist: $ROOT_FOLDER" >&2
    exit 1
fi

case "$MODE" in
    standard|forensic) ;;
    *)
        echo "ERROR: invalid --mode: $MODE (use standard or forensic)" >&2
        exit 1;;
esac

# Discover repos
TMP_REPOS=$(mktemp)
trap 'rm -f "$TMP_REPOS" 2>/dev/null || true' EXIT

log_info "🔍 Searching: $ROOT_FOLDER"
log_info "🔎 Looking for repos matching: ${REPO_NAME}*"

find_repos "$ROOT_FOLDER" "$REPO_NAME" "$TMP_REPOS"

if [[ ! -s "$TMP_REPOS" ]]; then
    log_error "No repos found matching prefix: ${REPO_NAME}*"
    exit 1
fi

case "$MODE" in
    standard)
        run_mode_standard "$TMP_REPOS"
        ;;
    forensic)
        run_mode_forensic "$TMP_REPOS"
        ;;
esac
